### ISSUE TITLE
Elegant solutions for Q16,17...

### ISSUE THREAD

**Issue by frankzhangsyd** [Ravin515/r-data-practice#1]
个人认为目前的写法有一些繁琐。(typing太多了)

完全可以先把`index_w50`,`index_w300`,`index_w500` melt一下再做，会容易很多。后面的几个问题也都可以用这个`tmp`来做

```r
tmp <- melt(dt,measure.vars = patterns("index"),variable.name = "Index_Name")
```

|symbol    |     date| pre_close| open| high|  low| close|    volume|     amount| adj_factor|         capt|industry |Index_Name |     value|
|:---------|--------:|---------:|----:|----:|----:|-----:|---------:|----------:|----------:|------------:|:--------|:----------|---------:|
|600000.SH | 20120104|      8.49| 8.54| 8.56| 8.39|  8.41|  34201379|  290229551|   6.655275| 125500555680|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120105|      8.41| 8.47| 8.82| 8.47|  8.65| 132116203| 1144753023|   6.655275| 129082022192|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120106|      8.65| 8.63| 8.78| 8.62|  8.71|  61778687|  537043761|   6.655275| 129977388820|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120109|      8.71| 8.72| 8.99| 8.68|  8.95|  80136249|  711429611|   6.655275| 133558855331|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120110|      8.95| 8.95| 9.10| 8.88|  9.07|  72004632|  647206633|   6.655275| 135349588587|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120111|      9.07| 9.05| 9.10| 8.98|  9.00|  49261157|  444366552|   6.655275| 134304994188|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120112|      9.00| 9.00| 9.21| 8.99|  9.09|  60486981|  551261471|   6.655275| 135648044130|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120113|      9.09| 9.11| 9.18| 8.97|  9.04|  56725332|  514638094|   6.655275| 134901905273|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120116|      9.04| 9.00| 9.12| 8.96|  8.97|  33100160|  299225053|   6.655275| 133857310874|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120117|      8.97| 9.00| 9.26| 8.79|  9.20|  97357263|  876457391|   6.655275| 137289549614|BANKS    |index_w50  | 0.0464093|
|600000.SH | 20120104|      8.49| 8.54| 8.56| 8.39|  8.41|  34201379|  290229551|   6.655275| 125500555680|BANKS    |index_w300 | 0.0212594|
|600000.SH | 20120105|      8.41| 8.47| 8.82| 8.47|  8.65| 132116203| 1144753023|   6.655275| 129082022192|BANKS    |index_w300 | 0.0212594|

再然后这样就好了。
```r
tmp[value>0,.(stkcd_amount=uniqueN(symbol)),by=.(Index_Name,type = ifelse(str_detect(symbol, "SH"), "SH", "SZ"))]
```

|Index_Name |type | stkcd_amount|
|:----------|:----|------------:|
|index_w50  |SH   |           54|
|index_w300 |SH   |          205|
|index_w300 |SZ   |           95|
|index_w500 |SH   |          297|
|index_w500 |SZ   |          248|

**Comment by Ravin515** [comment]
您好，感谢您提出的意见，我们已经采纳，code已经改写，请查看Q16-Q19，best wishes！！！

> 个人认为目前的写法有一些繁琐。(typing太多了)
> 
> 完全可以先把`index_w50`,`index_w300`,`index_w500` melt一下再做，会容易很多。后面的几个问题也都可以用这个`tmp`来做
> 
> ```r
> tmp <- melt(dt,measure.vars = patterns("index"),variable.name = "Index_Name")
> ```
> 
> symbol	date	pre_close	open	high	low	close	volume	amount	adj_factor	capt	industry	Index_Name	value
> 600000.SH	20120104	8.49	8.54	8.56	8.39	8.41	34201379	290229551	6.655275	125500555680	BANKS	index_w50	0.0464093
> 600000.SH	20120105	8.41	8.47	8.82	8.47	8.65	132116203	1144753023	6.655275	129082022192	BANKS	index_w50	0.0464093
> 600000.SH	20120106	8.65	8.63	8.78	8.62	8.71	61778687	537043761	6.655275	129977388820	BANKS	index_w50	0.0464093
> 600000.SH	20120109	8.71	8.72	8.99	8.68	8.95	80136249	711429611	6.655275	133558855331	BANKS	index_w50	0.0464093
> 600000.SH	20120110	8.95	8.95	9.10	8.88	9.07	72004632	647206633	6.655275	135349588587	BANKS	index_w50	0.0464093
> 600000.SH	20120111	9.07	9.05	9.10	8.98	9.00	49261157	444366552	6.655275	134304994188	BANKS	index_w50	0.0464093
> 600000.SH	20120112	9.00	9.00	9.21	8.99	9.09	60486981	551261471	6.655275	135648044130	BANKS	index_w50	0.0464093
> 600000.SH	20120113	9.09	9.11	9.18	8.97	9.04	56725332	514638094	6.655275	134901905273	BANKS	index_w50	0.0464093
> 600000.SH	20120116	9.04	9.00	9.12	8.96	8.97	33100160	299225053	6.655275	133857310874	BANKS	index_w50	0.0464093
> 600000.SH	20120117	8.97	9.00	9.26	8.79	9.20	97357263	876457391	6.655275	137289549614	BANKS	index_w50	0.0464093
> 600000.SH	20120104	8.49	8.54	8.56	8.39	8.41	34201379	290229551	6.655275	125500555680	BANKS	index_w300	0.0212594
> 600000.SH	20120105	8.41	8.47	8.82	8.47	8.65	132116203	1144753023	6.655275	129082022192	BANKS	index_w300	0.0212594
> 再然后这样就好了。
> 
> ```r
> tmp[value>0,.(stkcd_amount=uniqueN(symbol)),by=.(Index_Name,type = ifelse(str_detect(symbol, "SH"), "SH", "SZ"))]
> ```
> 
> Index_Name	type	stkcd_amount
> index_w50	SH	54
> index_w300	SH	205
> index_w300	SZ	95
> index_w500	SH	297
> index_w500	SZ	248

**Comment by frankzhangsyd** [comment]
直接这样会好一些。`.SD`我感觉不是这么用的。

```r
melt(data, measure.vars = patterns("index"), variable.name = "index_name")[value > 0, .(stkcd_amount = uniqueN(symbol)), by = .(index_name, type = ifelse(stringr::str_detect(symbol, "SH"), "SH", "SZ"))]
```
 参考作者Matt的[回答](https://stackoverflow.com/a/15274104/7584138)

**Comment by Ravin515** [comment]
我已看了matt的回答，对于他提到的`.SD`我个人的理解在于，不能l对`.SD`使用以vector作为对象的函数，例如文中提到的`sum`。而dcast或者melt并不是以vector作为处理对象而是DT，`.SD`的格式也恰好是DT，所以我个人理解这么做也是可行的，并不会造成matt所说的slow的问题。
> 直接这样会好一些。`.SD`我感觉不是这么用的。
> 
> ```r
> melt(data, measure.vars = patterns("index"), variable.name = "index_name")[value > 0, .(stkcd_amount = uniqueN(symbol)), by = .(index_name, type = ifelse(stringr::str_detect(symbol, "SH"), "SH", "SZ"))]
> ```
> 
> 参考作者Matt的[回答](https://stackoverflow.com/a/15274104/7584138)

**Comment by yu-soong** [comment]
这个有更优雅的方法
```
data[,
     purrr::map(.SD, ~ sum(.x > 0)),
     .SDcols = c("index_w50", "index_w300", "index_w500"),
     by = .(date, exchange = fifelse(symbol %like% "SH$", "SH", "ZH"))]
```
不过我觉得不用group by date了，因为没有问每天。
所以应该是：

```
data[,
     purrr::map(.SD, ~ sum(.x > 0)),
     .SDcols = c("index_w50", "index_w300", "index_w500"),
     by = .(exchange = fifelse(symbol %like% "SH$", "SH", "ZH"))]
```
当然也可以不用 purrr 包，用lapply：

```
data[,
     lapply(.SD, function(x) sum(x > 0)),
     .SDcols = patterns("index_"),
     by = .(exchange = fifelse(symbol %like% "SH$", "SH", "ZH"))]
```

**Comment by frankzhangsyd** [comment]
> 这个有更优雅的方法
> 
> ```
> data[,
>      purrr::map(.SD, ~ sum(.x > 0)),
>      .SDcols = c("index_w50", "index_w300", "index_w500"),
>      by = .(date, exchange = fifelse(symbol %like% "SH$", "SH", "ZH"))]
> ```
> 
> 不过我觉得不用group by date了，因为没有问每天。
> 所以应该是：
> 
> ```
> data[,
>      purrr::map(.SD, ~ sum(.x > 0)),
>      .SDcols = c("index_w50", "index_w300", "index_w500"),
>      by = .(exchange = fifelse(symbol %like% "SH$", "SH", "ZH"))]
> ```
> 
> 当然也可以不用 purrr 包，用lapply：
> 
> ```
> data[,
>      lapply(.SD, function(x) sum(x > 0)),
>      .SDcols = patterns("index_"),
>      by = .(exchange = fifelse(symbol %like% "SH$", "SH", "ZH"))]
> ```

Result的结构不一样 🤣 
弄成你这种宽形式的话肯定不用melt的

**Comment by yu-soong** [comment]
这个Result的结构就是原始的数据结构啊，有什么问题吗？

Yu Song

________________________________
