### ISSUE TITLE
Add solutions from `zoo` package for rolling aggregation questions (ie Q10)

### ISSUE THREAD

**Issue by frankzhangsyd** [Ravin515/r-data-practice#2]
滚动相关的计算题可以加一个`zoo`package的解法。

本来处理这种时间序列就是`zoo`的强项，就不用自己再造轮子了。

我觉得你们的解法都可以留着，不同的思路都很好。

例如Q10,38-40...

Q10:

```r
data_ex9[, .(date, n_openlimit_3d = zoo::rollapplyr(n_openlimit, width = 4, fill = NA, function(x) sum(x[-4])))]
```
参考：
[rollapply](https://www.rdocumentation.org/packages/zoo/versions/1.8-6/topics/rollapply)

**Comment by Ravin515** [comment]
感谢你的建议，zoo这个包的函数我们也经常会用，例如na.locf，非常棒的建议！！！
> 滚动相关的计算题可以加一个`zoo`package的解法。
> 
> 本来处理这种时间序列就是`zoo`的强项，就不用自己再造轮子了。
> 
> 我觉得你们的解法都可以留着，不同的思路都很好。
> 
> 例如Q10,38-40...
> 
> Q10:
> 
> ```r
> data_ex9[, .(date, n_openlimit_3d = zoo::rollapplyr(n_openlimit, width = 4, fill = NA, function(x) sum(x[-4])))]
> ```
> 
> 参考：
> [rollapply](https://www.rdocumentation.org/packages/zoo/versions/1.8-6/topics/rollapply)

**Comment by XiaomoWu** [comment]
感谢你的建议，在这里分享一下自己的使用`zoo`的体验。滚动回归我一开始就考虑用`zoo`，但是发现`zoo`在大数据集下的性能非常堪忧。记得以前自己做过一个实验，某些条件下`data.table`能够有10x至100x的性能提升。另外一个直观的使用体验是：`na.locf`这个函数看似很美好，但是在千万级观测时运行的时间常常无法忍受。

我们会逐步加入`zoo`的解法（毕竟它的语法更为简洁），同时会指出什么时候用`rollapply`是适用的，什么时候则不得不考虑性能更好的解法。

**Comment by frankzhangsyd** [comment]
有道理. 我目前还没有接触过这种情况哈哈 
另外公众号文章里我的名字少打了一个s...

有空的话可以做下测试，看看超过多少之后`zoo`就拖后腿了
