### ISSUE TITLE
A problem in group

### ISSUE THREAD

**Issue by StephenLee1029** [Ravin515/r-data-practice#3]
Q28，在取每天成交额前10%的股票时出现了错误，变成取出成交额高于所有股票前10%的股票，所以导致求平均收益时出现了偏差。我的做法是用.SD先取出每天成交额前10%的股票，然后进一步计算，不过有点繁琐。谢谢！

**Comment by Ravin515** [comment]
已修改，请查看最新版本的答案解析，谢谢！！
