### ISSUE TITLE
21题中的权重问题

### ISSUE THREAD

**Issue by thegreenflamingo** [Ravin515/r-data-practice#4]
您好！首先感谢猫哥还有其他前辈们提供的答案，收获了很多~
有一个问题想请教下，在第21题中，从沪深300中去掉了上证50的成分股，这样的话仍然留下的那些沪深300成分股权重就会相应发生变化。
虽然在最后计算cor的时候，不管是否重新调整权重答案都一样，但是请问下如何写“readjust weight”的语句呢？谢谢您~
r语言小白。。。

**Comment by Ravin515** [comment]
你能够再说得详细一点吗？你所说的readjust weight是怎样的？

**Comment by zhjx19** [comment]
有若干道计算变化率的题目，还用for循环实现太啰嗦了，直接这样就可以了：
amount_change = (amount - lag(amount)) / lag(amount)

**Comment by zhjx19** [comment]
还有group_by+summarise(n())， 可以直接用count()

**Comment by zhjx19** [comment]
10题，计算最近3天加和，可以用
slider::slide_dbl(lag(num), sum, .before = 2)

**Comment by Ravin515** [comment]
> 10题，计算最近3天加和，可以用
> slider::slide_dbl(lag(num), sum, .before = 2)

你好，感谢你的建议，如果可以的话，请重新开一个issue，谢谢！！
