### ISSUE TITLE
若干优化代码的建议

### ISSUE THREAD

**Issue by zhjx19** [Ravin515/r-data-practice#5]
有若干道计算变化率的题目，还用for循环实现太啰嗦了，直接这样就可以了：
amount_change = (amount - lag(amount)) / lag(amount)

**Comment by zhjx19** [comment]
还有group_by+summarise(n())， 可以直接用count()

**Comment by zhjx19** [comment]
10题，计算最近3天加和，可以用
slider::slide_dbl(lag(num), sum, .before = 2)

**Comment by Ravin515** [comment]
> 有若干道计算变化率的题目，还用for循环实现太啰嗦了，直接这样就可以了：
> amount_change = (amount - lag(amount)) / lag(amount)

感谢您的建议，这些题目我们会直接选用data.table包中的shift进行修改。

**Comment by Ravin515** [comment]
> 还有group_by+summarise(n())， 可以直接用count()

感谢您的建议，这部分应该是利用dplyr进行处理的部分，具体您可以直接与@香酥奶油饼（微信）进行交流。

**Comment by Ravin515** [comment]
> 10题，计算最近3天加和，可以用
> slider::slide_dbl(lag(num), sum, .before = 2)

感谢您的建议，这个函数我们会考虑加入到修改当中。

**Comment by Ravin515** [comment]
> 10题，计算最近3天加和，可以用
> slider::slide_dbl(lag(num), sum, .before = 2)

此题无法运用这一函数，可参考新修改的习题10村长的答案解析
